### ISSUE TITLE
Homepage throwing JS error in Chrome

### ISSUE THREAD

**Issue by cfjedimaster** [mozbrick/brick#56] opened 2013-09-13 02:26 UTC
Getting this in Chrome dev tools and the 'flip' demo won't work:

Uncaught TypeError: Cannot read property 'labels' of undefined brick.js:2

**Comment by ldoubleuz** [comment] 2013-09-13 02:31
I'm unable to reproduce this. What version of Chrome are you using?

**Comment by cfjedimaster** [comment] 2013-09-13 02:31
Version 29.0.1547.65

**Comment by ldoubleuz** [comment] 2013-09-13 02:36
Hmm, that's pretty much the same version I'm using. What timezone/region are you in?

**Comment by cfjedimaster** [comment] 2013-09-13 02:37
CST. Um, Louisiana. Doubt that matters. ;)

On Thu, Sep 12, 2013 at 9:36 PM, Leon Zhang notifications@github.comwrote:

> Hmm, that's pretty much the same version I'm using. What timezone/region
> are you in?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/brick/issues/56#issuecomment-24369686
> .

## 

# 

Raymond Camden, Adobe Developer Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: cfjedimaster

**Comment by ldoubleuz** [comment] 2013-09-13 02:43
Does the crash occur if you visit the flipbox demo page itself? What about when you visit this testpage: http://mozilla.github.io/brick/component/flipbox/demo/testpage.html ?

**Comment by cfjedimaster** [comment] 2013-09-13 02:45
Flips work fine on the test page. On the demo page (
http://mozilla.github.io/brick/demos/flipbox/index.html) it fails with the
same error.

On Thu, Sep 12, 2013 at 9:43 PM, Leon Zhang notifications@github.comwrote:

> Does the crash occur if you visit the flipbox demo page itself? What about
> when you visit this testpage:
> http://mozilla.github.io/brick/component/flipbox/demo/testpage.html ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/brick/issues/56#issuecomment-24369925
> .

## 

# 

Raymond Camden, Adobe Developer Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: cfjedimaster

**Comment by ldoubleuz** [comment] 2013-09-13 02:48
Hmm, the only components that I can think of that could be using a labels property are x-calendars and x-datepickers. Can you let me know if either of the following testpages reproduces the error? 
http://mozilla.github.io/brick/component/calendar/demo/testpage.html
http://mozilla.github.io/brick/component/datepicker/demo/testpage.html

**Comment by cfjedimaster** [comment] 2013-09-13 03:22
First returns: Uncaught TypeError: Cannot call method 'render' of undefined 
Second returns the earlier error: TypeError: Cannot read property 'labels' of undefined [http://mozilla.github.io/brick/component/calendar/src/calendar.js:1726]

**Comment by ldoubleuz** [comment] 2013-09-13 04:47
Hmm, I still can't reproduce the issue you're seeing. Can you tell me more about the environment you're running in? 

Also, what line is the crash reporting for "Uncaught TypeError: Cannot call method 'render' of undefined" on the calendar test page?

**Comment by cfjedimaster** [comment] 2013-09-13 10:48
Line # for error is calendar.js 1749

As for environment, OSX. Not sure what else I can tell you though.

**Comment by jeluard** [comment] 2013-09-18 23:03
I have a similar issue with latest Chrome Canary. No error message but `toggle` doesn't do anything.
This is with `#enable-experimental-web-platform-features` enabled in `chrome://flags` (disabled by default). Without the flag enabled it works as expected.

**Comment by pennyfx** [comment] 2013-09-19 06:43
@csuwldcat This sounds like the polyfill and Chromes native implementation may have diverged.

**Comment by fwenzel** [comment] 2013-09-24 09:55
@pennyfx Will you file an upstream bug and fix this, presumably on the x-tag level? Thanks

**Comment by pennyfx** [comment] 2013-09-24 18:16
@potch I pulled in the latest polyfill changes that fixes this issue and updated Brick's ref to x-tag-core.  We're at tag 0.8.2 now.   Can you rebuild the site?

**Comment by csuwildcat** [comment] 2013-09-26 19:26
Can we get a report on whether or not this is fixed as a result of the recent changes?

**Comment by cfjedimaster** [comment] 2013-09-26 19:30
I still get an error on the site.

**Comment by pennyfx** [comment] 2013-09-26 19:31
@potch Is the site updated?

**Comment by csuwildcat** [comment] 2013-09-26 19:42
@potch we updated the library a couple days ago, did the site ever get recompiled with that new version?

**Comment by potch** [comment] 2013-09-27 20:45
We just updated the site. @cfjedimaster curious if you still see the issue.

**Comment by cfjedimaster** [comment] 2013-09-27 20:52
Sorry but no guys. Same bug. Cleared cache even.

On Fri, Sep 27, 2013 at 3:45 PM, Potch notifications@github.com wrote:

> We just updated the site. @cfjedimaster https://github.com/cfjedimastercurious if you still see the issue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/brick/issues/56#issuecomment-25275998
> .

## 

# 

Raymond Camden, Adobe Developer Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: cfjedimaster

**Comment by potch** [comment] 2013-09-27 21:08
I'm at a loss here. Can you send me the full contents of the brick.js you're seeing? Feel free to drop it in a pastebin/gist.

**Comment by cfjedimaster** [comment] 2013-09-27 21:11
Posted here:
https://gist.github.com/cfjedimaster/6735251

On Fri, Sep 27, 2013 at 4:08 PM, Potch notifications@github.com wrote:

> I'm at a loss here. Can you send me the full contents of the brick.js
> you're seeing? Feel free to drop it in a pastebin/gist.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/brick/issues/56#issuecomment-25277449
> .

## 

# 

Raymond Camden, Adobe Developer Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: cfjedimaster

**Comment by cfjedimaster** [comment] 2013-09-27 21:12
As an FYI, it works in Canary. As I said, I did clear my cache in my main
Chrome though.

On Fri, Sep 27, 2013 at 4:11 PM, Raymond Camden raymondcamden@gmail.comwrote:

> Posted here:
> https://gist.github.com/cfjedimaster/6735251
> 
> On Fri, Sep 27, 2013 at 4:08 PM, Potch notifications@github.com wrote:
> 
> > I'm at a loss here. Can you send me the full contents of the brick.js
> > you're seeing? Feel free to drop it in a pastebin/gist.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/mozilla/brick/issues/56#issuecomment-25277449
> > .
> 
> ## 
> 
> # 
> 
> Raymond Camden, Adobe Developer Evangelist
> 
> Email : raymondcamden@gmail.com
> Blog : www.raymondcamden.com
> Twitter: cfjedimaster

## 

# 

Raymond Camden, Adobe Developer Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: cfjedimaster

**Comment by potch** [comment] 2013-09-27 21:21
ah ha! Do you have "Enable Experimental WebKit Features" turned on in about:flags? I can immediately repro when I flip that flag on. I'm not certain who's at fault there, but turning that off should fix you.

**Comment by cfjedimaster** [comment] 2013-09-27 21:24
Yep, that was it. Let's blame Google - they can handle it.

On Fri, Sep 27, 2013 at 4:21 PM, Potch notifications@github.com wrote:

> ah ha! Do you have "Enable Experimental WebKit Features" turned on in
> about:flags? I can immediately repro when I flip that flag on. I'm not
> certain who's at fault there, but turning that off should fix you.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/brick/issues/56#issuecomment-25278213
> .

## 

# 

Raymond Camden, Adobe Developer Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: cfjedimaster

**Comment by potch** [comment] 2013-09-27 22:18
We should investigate whether we're exploding due to a bug in Chrome's impl of Custom Elements, or a bug in the polyfill.

**Comment by csuwildcat** [comment] 2013-09-27 22:19
I'm on PTO, but I can try to hunt this down early tomorrow morning.

**Comment by potch** [comment] 2013-09-27 22:21
awesome.

**Comment by csuwildcat** [comment] 2013-09-28 11:33
Does anyone who is seeing this issue have experimental web features flags/configs pref'd on in their browser? If so, the WIP native browser implementations are outdated and will cause the shared Mozilla/Google polyfill to fail.

Please test this issue with no flags/configs on and let us know the results! ;)

**Comment by jeluard** [comment] 2013-09-28 11:42
Yes it does work fine with the flag disabled on Chrome Canary. That said polymer examples and my own experimentation with web components technologies work fine on Canary with the flag enabled.

**Comment by csuwildcat** [comment] 2013-09-28 11:48
Not trying to be negative to you, but that's almost impossible - we share
70% of the base code with Polymer via a collaborative polyfill both libs
use, and X-Tag touches nothing experimental in its Core code. Basically,
all the stuff that would break due to prefs being on happens in the
polyfill.

**Comment by csuwildcat** [comment] 2013-09-28 11:52
@potch can you put a warning up on the site ASAP about having experimental web features pref'd on causing bustage due to outdated native WIP implementations in Chrome/Firefox? This is the 3rd time this week we've seen people trip over this issue :/

**Comment by jeluard** [comment] 2013-09-28 23:27
Sure I understand! That said bugs happen ;)

By the way here is how I see x-tags.org with the same flag enabled:

![capture decran 2013-09-28 a 20 19 28](https://f.cloud.github.com/assets/359723/1232187/6dc97650-2895-11e3-97b5-ae54fa290317.png)

**Comment by csuwildcat** [comment] 2013-09-28 23:37
Yeah, unfortunately the browser WIP implementations are months old and
break the polyfill. I'd just leave flags off at this point - we're
weeks-to-months from having full candidate implementation in browsers.

**Comment by potch** [comment] 2013-10-18 04:14
I'm closing this up.

**Closed as completed by potch** 2013-10-18 04:14 UTC
