### ISSUE TITLE
update tabbar example to have a default selected tab

### ISSUE THREAD

**Issue by nickdesaulniers** [mozbrick/brick#172] opened 2014-05-07 00:04 UTC
from [with x-deck](http://mozilla.github.io/brick/demos/x-tag-tabbar/index.html)

**Comment by fwenzel** [comment] 2014-05-07 23:52
Yeah I think that makes sense.

**Comment by tofumatt** [comment] 2014-05-10 13:35
Filed a pull request with x-tag and also #173 because of how this system is a bit wonky.

Once the code is landed in x-tag and we update the bower version here this can be fixed.

**Comment by potch** [comment] 2014-06-03 18:13
Wonkiness confirmed. We're going to move Brick-specific demos to the brick repository and let individual components do their own demos if they so desire.

**Comment by potch** [comment] 2014-07-16 21:19
We're re-doing the demo pages- will make sure the new demo has this.

**Closed as completed by potch** 2014-07-16 21:19 UTC
