### ISSUE TITLE
Build Bundle with 0 components selected do nothing 

### ISSUE THREAD

**Issue by sonnyp** [mozbrick/brick#128] opened 2014-02-20 14:44 UTC
http://mozilla.github.io/brick/download.html

The progress bar will fill and nothing else happens.

**Comment by fwenzel** [comment] 2014-02-20 18:00
Good find!

**Comment by sole** [comment] 2014-02-20 18:44
Dupe of #127 ? which is supposedly fixed? Maybe a gh-pages push is in order

**Comment by pennyfx** [comment] 2014-02-20 19:32
Ya, it's fixed.  Just need to update the site.  

@potch

**Comment by potch** [comment] 2014-02-20 19:38
Doing this right now!

**Comment by sole** [comment] 2014-02-20 19:39
Is there any special process before deploying to gh-pages? some sort of build script that needs to be run? It'd be good to know just in case we need emergency out-of-PST support ;-)

**Comment by sole** [comment] 2014-02-24 19:51
closed as duplicate of #127

**Closed as completed by sole** 2014-02-24 19:51 UTC
