### ISSUE TITLE
Calendar Control - IE10 Bug

### ISSUE THREAD

**Issue by chriseaton** [mozbrick/brick#43] opened 2013-08-28 22:15 UTC
On the calendar "Basic calendar with navigation controls" demo here:
http://mozilla.github.io/brick/demos/calendar/index.html

If you click the _previous month_ arrow several times eventually the calendar will disappear and insert a huge grey line through the center of the entire page (see attached image).

![ie10](https://f.cloud.github.com/assets/5247568/1045960/2e18af68-102f-11e3-94cf-348cd64d3e3c.png)

System is Windows 7 - IE 10.0.9200

**Comment by potch** [comment] 2013-08-29 07:22
Looking at reproducing it. We've had issues with calendar before - what locale/timezone are you in?

**Comment by ldoubleuz** [comment] 2013-09-03 00:44
This was caused by an error in the logic of converting a "local" Date to be in the UTC timezone in certain edge cases. Fixed as of abae764eacb3f0e08082ad0d08efb7146a548703

**Closed as completed by ldoubleuz** 2013-09-03 00:44 UTC
Labels: bug
