### ISSUE TITLE
Is the calendar Demo broken ? It always displays only 1 date

### ISSUE THREAD

**Issue by shidhincr** [mozbrick/brick#28] opened 2013-08-17 03:05 UTC
I went to the calendar demo in this url

http://mozilla.github.io/brick/component/calendar/demo/index.html

There I can see only one date for each examples. Is it a bug ?

**Comment by bcbcarl** [comment] 2013-08-17 06:24
Me, too. I can only see one date here.

**Comment by ldoubleuz** [comment] 2013-08-17 07:56
Hmm, what browsers are you using? Also, what region are you in? This could possibly be caused by non-US dateformats, similar to https://github.com/mozilla/brick/issues/25. 

Someone offsite reported something similar, where it only displays "21" over and over. Is this similar to what you are seeing?

**Comment by bcbcarl** [comment] 2013-08-17 08:04
It looks just like this:
![(Calendar screenshot)](http://i.imgur.com/bEz7Lpe.png)

**Comment by ldoubleuz** [comment] 2013-08-17 08:05
Do you happen to be based in the UK or some other region with a non-US date format? Also, what browser are you using?

**Comment by bcbcarl** [comment] 2013-08-17 08:07
I use the latest version of Mozilla Firefox and Google Chrome.

Same problems here even I changed my date and time formats.
Mozilla Firefox 24.0b1 (en-US) didn't work properly either.
This problem existing under Windows 7 and Arch Linux.

![(date and time formats)](http://i.imgur.com/q0MNil2.png)

**Comment by colingourlay** [comment] 2013-08-17 12:08
Same issue here using Google Chrome from Australia
http://glui.me/?i=zismqomriauuksp/2013-08-17_at_10.07_PM_2x.png/

**Comment by shidhincr** [comment] 2013-08-18 13:54
I am using Google chrome , MacOS and from India. Issue still persist for me

**Comment by ldoubleuz** [comment] 2013-08-19 01:40
Fixed as of version [1.0.3beta](https://github.com/mozilla/brick/releases/tag/1.0.3beta)

**Closed as completed by ldoubleuz** 2013-08-19 01:40 UTC
Labels: bug
