### ISSUE TITLE
problem building brick

### ISSUE THREAD

**Issue by arasbm** [mozbrick/brick#72] opened 2013-09-30 02:28 UTC
I am trying to build brick, but I am getting this error:

```
[~/Projects/brick(master)]$ make
running 'git submodule update --init --recursive'...
fatal: reference is not a tree: 3724b30298fe86a101afa7ff80501d320161d29d
fatal: reference is not a tree: 7e7c7e90f714d8834fbf49489ab9dd8cebb4d5cd
fatal: reference is not a tree: 5bed2236ab958adab07e227b22dd4b9a1c2d054d
Unable to checkout '3724b30298fe86a101afa7ff80501d320161d29d' in submodule path 'lib/CustomElements'
Unable to checkout '7e7c7e90f714d8834fbf49489ab9dd8cebb4d5cd' in submodule path 'lib/HTMLImports'
Unable to checkout '5bed2236ab958adab07e227b22dd4b9a1c2d054d' in submodule path 'lib/MutationObservers'
Failed to recurse into submodule path 'component/core/src/x-tag-core'
make: *** [components] Error 1
```

It would be great if someone could what the cause is, and what I could do to fix it. Thanks!

**Comment by potch** [comment] 2013-10-01 03:55
Closing this as a dupe of #72.

**Closed as completed by potch** 2013-10-01 03:55 UTC
